# Generated by Django 5.2.1 on 2025-06-02 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0007_alter_clubmember_student_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date_time", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
                ("organizer_name", models.CharField(max_length=255)),
                ("organizer_contact", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("internal", "Internal")],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("no_registration", "No Registration Required"),
                            ("registration_required", "Registration Required"),
                        ],
                        max_length=30,
                    ),
                ),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "poster",
                    models.ImageField(
                        blank=True, null=True, upload_to="event_posters/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="clubs.club",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("affiliation", models.CharField(max_length=100)),
                ("custom_answers", models.JSONField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("cancellation_requested", models.BooleanField(default=False)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_in", models.BooleanField(default=False)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="events.event",
                    ),
                ),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.eventregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistrationQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=255)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_questions",
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
