# Generated by Django 5.1.5 on 2025-05-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClubRegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club_username", models.CharField(max_length=150, unique=True)),
                ("club_password", models.CharField(max_length=128)),
                ("club_name", models.CharField(max_length=255)),
                ("club_category", models.CharField(max_length=255)),
                ("date_established", models.DateField()),
                ("president_name", models.CharField(max_length=255)),
                ("president_student_id", models.CharField(max_length=50)),
                ("president_email", models.EmailField(max_length=254)),
                ("president_phone", models.CharField(max_length=20)),
                ("president_department_year", models.CharField(max_length=255)),
                ("secretary_name", models.CharField(max_length=255)),
                ("secretary_student_id", models.CharField(max_length=50)),
                ("secretary_email", models.EmailField(max_length=254)),
                ("secretary_phone", models.CharField(max_length=20)),
                ("secretary_department_year", models.CharField(max_length=255)),
                ("treasurer_name", models.CharField(blank=True, max_length=255)),
                ("treasurer_student_id", models.CharField(blank=True, max_length=50)),
                ("treasurer_email", models.EmailField(blank=True, max_length=254)),
                ("treasurer_phone", models.CharField(blank=True, max_length=20)),
                (
                    "treasurer_department_year",
                    models.CharField(blank=True, max_length=255),
                ),
                ("other_executive_members", models.TextField(blank=True)),
                ("club_constitution", models.TextField()),
                ("mission_and_vision", models.TextField()),
                ("membership_rules", models.TextField(blank=True)),
                ("advisor_name", models.CharField(blank=True, max_length=255)),
                ("advisor_contact", models.CharField(blank=True, max_length=255)),
                ("facebook_link", models.URLField(blank=True)),
                ("instagram_link", models.URLField(blank=True)),
                ("linkedin_link", models.URLField(blank=True)),
                ("youtube_link", models.URLField(blank=True)),
                ("website_link", models.URLField(blank=True)),
                ("is_approved", models.BooleanField(default=False)),
            ],
        ),
    ]
