# Generated by Django 5.1.5 on 2025-05-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClubRegistrationRequest",
            new_name="ClubRegistration",
        ),
    ]
