# Generated by Django 5.1.5 on 2025-05-27 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_rename_clubregistrationrequest_clubregistration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clubregistration",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clubregistration",
            name="club_constitution",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="clubregistration",
            name="mission_and_vision",
            field=models.TextField(blank=True),
        ),
    ]
