# Generated by Django 5.2.1 on 2025-06-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_alter_clubregistration_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubregistration",
            name="organizing_secretary_department",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="clubregistration",
            name="organizing_secretary_session",
            field=models.CharField(max_length=20),
        ),
    ]
