# Generated by Django 5.1.5 on 2025-05-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_clubregistration_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubregistration",
            name="user",
        ),
    ]
