# Generated by Django 5.2.1 on 2025-06-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clubs",
            "0003_alter_clubregistration_organizing_secretary_department_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubregistration",
            name="president_department",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="clubregistration",
            name="president_session",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="clubregistration",
            name="secretary_department",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="clubregistration",
            name="secretary_session",
            field=models.CharField(max_length=20),
        ),
    ]
