# Generated by Django 5.2.1 on 2025-06-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0004_alter_clubregistration_president_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubregistration",
            name="review_notes",
        ),
        migrations.RemoveField(
            model_name="clubregistration",
            name="status",
        ),
        migrations.AddField(
            model_name="clubregistration",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
