# Generated by Django 5.2.1 on 2025-06-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_remove_clubregistration_review_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="leave_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="member_photos/"),
        ),
    ]
