# Generated by Django 5.1.5 on 2025-05-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_club_clubadvisor_clubmember_clubsociallink"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="cover_photo",
            field=models.ImageField(blank=True, null=True, upload_to="club_covers/"),
        ),
        migrations.AddField(
            model_name="club",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="club_logos/"),
        ),
    ]
