# Generated by Django 5.1.5 on 2025-05-29 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_club_cover_photo_club_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubregistration",
            name="approved_club",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clubs.club",
            ),
        ),
    ]
