# Generated by Django 5.2.1 on 2025-06-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_clubmember_leave_date_clubmember_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmember",
            name="student_id",
            field=models.CharField(max_length=50),
        ),
    ]
