# Generated by Django 5.2.1 on 2025-05-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_clubregistration_approved_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("president", "President"),
                    ("vice_president", "Vice President"),
                    ("secretary", "Secretary"),
                    ("joint_secretary", "Joint Secretary"),
                    ("assistant_secretary", "Assistant Secretary"),
                    ("treasurer", "Treasurer"),
                    ("financial_controller", "Financial Controller"),
                    ("event_manager", "Event Manager"),
                    ("event_coordinator", "Event Coordinator"),
                    ("logistics_head", "Logistics Head"),
                    ("operations_manager", "Operations Manager"),
                    ("pr_officer", "Public Relations Officer"),
                    ("communications_officer", "Communications Officer"),
                    ("media_coordinator", "Media Coordinator"),
                    ("social_media_manager", "Social Media Manager"),
                    ("creative_director", "Creative Director"),
                    ("design_head", "Design Head"),
                    ("technical_head", "Technical Head"),
                    ("content_creator", "Content Creator"),
                    ("graphic_designer", "Graphic Designer"),
                    ("webmaster", "Webmaster"),
                    ("photographer", "Photographer"),
                    ("videographer", "Videographer"),
                    ("membership_coordinator", "Membership Coordinator"),
                    ("outreach_coordinator", "Outreach Coordinator"),
                    ("partnership_coordinator", "Partnership Coordinator"),
                    ("fundraising_officer", "Fundraising Officer"),
                    ("alumni_relations", "Alumni Relations Officer"),
                    ("cultural_secretary", "Cultural Secretary"),
                    ("sports_secretary", "Sports Secretary"),
                    ("academic_head", "Academic Head"),
                    ("research_head", "Research Head"),
                    ("training_head", "Training Head"),
                    ("welfare_officer", "Welfare Officer"),
                    ("equity_officer", "Equity Officer"),
                    ("faculty_advisor", "Faculty Advisor"),
                    ("mentor", "Mentor"),
                    ("legal_advisor", "Legal Advisor"),
                    ("auditor", "Auditor"),
                    ("project_manager", "Project Manager"),
                    ("volunteer_coordinator", "Volunteer Coordinator"),
                    ("general_member", "General Member"),
                    ("executive_member", "Executive Member"),
                ],
                max_length=30,
            ),
        ),
    ]
